### ISSUE TITLE
xinetd service always running on port 20015

### ISSUE THREAD

**Issue by oyearunpal** [xinetd-org/xinetd#36]
I have added following line in /etc/xinetd.conf under default section
`        port            =  5667`
But my xinetd service is not taking that port, instead, it is running on 20015 only.

Following is my box configuration

```
[root@localhost etc]# cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.2"
```

**Comment by ltworf** [comment]
Probably misconfigured. I assure you xinetd works.

Send your entire xinetd configuration, including all the files in `/etc/xinetd.d/`

**Comment by oyearunpal** [comment]
Here are
[xinted.zip](https://github.com/xinetd-org/xinetd/files/8126393/xinted.zip)

**Comment by ltworf** [comment]
I don't see anything weird there

what's the output for `sudo netstat -lnpt`?

**Comment by oyearunpal** [comment]
[root@localhost ~]# sudo netstat -lnpt|grep xinetd
tcp6       0      0 :::20015                :::*                    LISTEN      3191703/xinetd

**Comment by vapier** [comment]
you can run `xinetd -d -filelog /dev/stderr` to see what it's doing if you don't know how to change the service's flags or read the normal syslog

**Comment by oyearunpal** [comment]
Thanks team. I found the issue on my configuration file. After enabling nrpe service i.e setting `disable = no` it started running on port 5666
```
service nrpe
{
    disable         = no
    socket_type     = stream
    port            = 5666
...
```
